# -*- coding: utf-8 -*-
"""Traps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqFIqB_7AtGylSMEFqFBtSTopfI57MrV
"""

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X,y=make_classification(n_samples=1000,n_features=10,random_state=42)
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(X_train,y_train)
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)
train_acc=accuracy_score(y_train,y_train_pred)
test_acc=accuracy_score(y_test,y_test_pred)
print("Train Accuracy:",train_acc)
print("Test Accuracy:",test_acc)

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
X,y=make_classification(n_samples=1000,n_features=10,random_state=42)
X_tain,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
pipeline=Pipeline([('scaler',StandardScaler()),('model',LogisticRegression())])
cv_scores=cross_val_score(pipeline,X_train,y_train,cv=5)
print("Cross-validation scores:",cv_scores)
print("Mean :",np.mean(cv_scores))
print("Standard Deviation :",np.std(cv_scores))

from sklearn.tree import DecisionTreeClassifier
depths=[1,5,20]
results=[]
for depth in depths:
    model=DecisionTreeClassifier(max_depth=depth,random_state=42)
    model.fit(X_train,y_train)
    train_acc=model.score(X_train,y_train)
    test_acc=model.score(X_test,y_test)
    results.append((depth,train_acc,test_acc))
print("Depth  |   Train Accuracy  |   Test Accuracy")
for result in results:
    print(f"{result[0]}   |{result[1]:.4f}    |{result[2]:.4f}")